version: "3.9"

services:
  postgress_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  postgres_data:
networks:
  default:
    name: default-network-dbs
